[package]
name = 'governance'
version = '1.0.0'

[dependencies]
AptosFramework = { git = 'https://github.com/davidiw/aptos-core.git', rev = 'conversions', subdir = 'aptos-move/framework/aptos-framework' }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

movedao = "0x100000"
